net="$1"
way="$2"
mkdir ../results/seq_gen/${net}
for model in seq_32x1_16  seq_64x1_16  seq_32x2_16  seq_32_32  seq_32x1_16_filt3  seq_emb_32x1_16; do
	mkdir ../results/seq_gen/${net}/${model}
	echo $model
	THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 10 0.005 ../data/seeds ${way} >log/${model}_${net}-0.005-10.log 2>&1 &
	THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 20 0.005 ../data/seeds ${way} >log/${model}_${net}-0.005-20.log 2>&1 & 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 30 0.005 ../data/seeds ${way} >log/${model}_${net}-0.005-30.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 40 0.005 ../data/seeds ${way} >log/${model}_${net}-0.005-40.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 50 0.005 ../data/seeds ${way} >log/${model}_${net}-0.005-50.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 60 0.005 ../data/seeds ${way} >log/${model}_${net}-0.005-60.log 2>&1 
	THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 70 0.005 ../data/seeds ${way} >log/${model}_${net}-0.005-70.log 2>&1 & 
	THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 10 0.0005 ../data/seeds ${way} >log/${model}_${net}-0.0005-10.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 20 0.0005 ../data/seeds ${way} >log/${model}_${net}-0.0005-20.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 30 0.0005 ../data/seeds ${way} >log/${model}_${net}-0.0005-30.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 40 0.0005 ../data/seeds ${way} >log/${model}_${net}-0.0005-40.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 50 0.0005 ../data/seeds ${way} >log/${model}_${net}-0.0005-50.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 60 0.0005 ../data/seeds ${way} >log/${model}_${net}-0.0005-60.log 2>&1 &
	THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 70 0.0005 ../data/seeds ${way} >log/${model}_${net}-0.0005-70.log 2>&1 &
	THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 10 0.001 ../data/seeds ${way} >log/${model}_${net}-0.001-10.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 20 0.001 ../data/seeds ${way} >log/${model}_${net}-0.001-20.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 30 0.001 ../data/seeds ${way} >log/${model}_${net}-0.001-30.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 40 0.001 ../data/seeds ${way} >log/${model}_${net}-0.001-40.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 50 0.001 ../data/seeds ${way} >log/${model}_${net}-0.001-50.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 60 0.001 ../data/seeds ${way} >log/${model}_${net}-0.001-60.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 70 0.001 ../data/seeds ${way} >log/${model}_${net}-0.001-70.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 10 5e-05 ../data/seeds ${way} >log/${model}_${net}-5e-05-10.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 20 5e-05 ../data/seeds ${way} >log/${model}_${net}-5e-05-20.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 30 5e-05 ../data/seeds ${way} >log/${model}_${net}-5e-05-30.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 40 5e-05 ../data/seeds ${way} >log/${model}_${net}-5e-05-40.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 50 5e-05 ../data/seeds ${way} >log/${model}_${net}-5e-05-50.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 60 5e-05 ../data/seeds ${way} >log/${model}_${net}-5e-05-60.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 70 5e-05 ../data/seeds ${way} >log/${model}_${net}-5e-05-70.log 2>&1 &
	THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 10 0.0001 ../data/seeds ${way} >log/${model}_${net}-0.0001-10.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 20 0.0001 ../data/seeds ${way} >log/${model}_${net}-0.0001-20.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 30 0.0001 ../data/seeds ${way} >log/${model}_${net}-0.0001-30.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 40 0.0001 ../data/seeds ${way} >log/${model}_${net}-0.0001-40.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 50 0.0001 ../data/seeds ${way} >log/${model}_${net}-0.0001-50.log 2>&1 
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 60 0.0001 ../data/seeds ${way} >log/${model}_${net}-0.0001-60.log 2>&1 &
        THEANO_FLAGS='floatX=float32,device=cuda,lib.cnmem=0.1' python utils/single_opt.py ../data/${net}/Lucentis_b/CV0/${model} ${model}_ ../results/seq_gen/${net}/${model}/ 70 0.0001 ../data/seeds ${way} >log/${model}_${net}-0.0001-70.log 2>&1 
done
